_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [0, 0, 0]
  BACKBONE:
    NAME: "build_efficientDet_with_detecttions_backbone"
    OUT_FEATURES: [ "p3", "p4", "p5" ]
#    OUT_FEATURES: [ "p2" ]
  MASK_ON: True
#  RESNETS:
#    OUT_FEATURES: [ "p2", "p3", "p4", "p5" ]
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: [ "p3", "p4", "p5" ]
#    IN_FEATURES: [ "p2" ]
    NUM_CLASSES: 1
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    POOLER_RESOLUTION: "14"
#  RESNETS:
#    DEPTH: 50
  BOX_ON: False
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.002
  STEPS: ( 600, 900, 1300)
  MAX_ITER: 2000
  WARMUP_ITERS: 100
INPUT:
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"
#  MAX_SIZE_TEST: 5000
#  MIN_SIZE_TEST: [1,5000]
  CROP:
    ENABLED: false
DATASETS:
  TRAIN: ("penn",)
  TEST: ("penn",)
VIS_PERIOD: 10